spring:
  application:
    name: SpringCoinRagSystem
  ai:
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: ${QDRANT_PORT:6334}
        api-key: ${QDRANT_API_KEY}
        collection-name: ${QDRANT_COLLECTION:articles-v2}
        use-tls: ${QDRANT_USE_TLS:true}
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        model: ${OLLAMA_EMBED_MODEL:nomic-embed-text}
        options:
          num-batch: ${OLLAMA_EMBED_BATCH:12}
          num-thread: ${OLLAMA_EMBED_THREADS:2}
          num-gpu: ${OLLAMA_EMBED_GPU:1}
          main-gpu: 0
      chat:
        model: ${OLLAMA_CHAT_MODEL:qwen2.5:3b-instruct}
        options:
          temperature: ${OLLAMA_TEMP:0.2}
          top-p: ${OLLAMA_TOP_P:0.9}
          top-k: ${OLLAMA_TOP_K:40}
          num-predict: ${OLLAMA_NUM_PREDICT:1000}
          repeat-penalty: ${OLLAMA_REPEAT_PENALTY:1}
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME:coin_rag_bot}
threads: ${APP_THREADS:8}
chunk:
  sentences: 4
coin-telegraph:
  parsing:
    time: ${PARSING_TIME:200}
