spring:
  application:
    name: SpringCoinRagSystem
  ai:
    vectorstore:
      qdrant:
        host: https://a8041701-a0fb-4e25-ab55-e5765123137a.europe-west3-0.gcp.cloud.qdrant.io
        api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.-hU4XcKgiF10egqEj_5LHdM8X00UdQTMUK5Xvuab8qo
        collection-name: articles
        use-tls: false
        initialize-schema: true
threads: 8
chunk:
  sentences: 4
embedding:
  ollama:
    url: http://localhost:11434/api/embeddings
    model: nomic-embed-text
    batch-size: 5
    max-concurrent: 3
chat:
  ollama:
    url: http://localhost:11434/api/completions
    model: gemma3:1b
